### ISSUE TITLE
源码编译失败，萌新求带，为什么会缺省一个ImageStreamListener

### ISSUE THREAD

**Issue by onlineDu** [asjqkkkk/flutter-todos#1]
![屏幕快照 2019-08-02 上午9 30 06](https://user-images.githubusercontent.com/53588397/62338220-501eb180-b50a-11e9-9ccf-1ab80d3e7aef.png)
Compiler message:
file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/image_crop-0.3.0/lib/src/crop.dart:87:3: Error: Type 'ImageStreamListener' not found.
  ImageStreamListener _imageListener;
  ^^^^^^^^^^^^^^^^^^^
F/crash_dump64(24342): crash_dump.cpp:472] failed to attach to thread 24337: Permission denied
file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/image_crop-0.3.0/lib/src/crop.dart:87:3: Error: 'ImageStreamListener' isn't a type.
  ImageStreamListener _imageListener;
  ^^^^^^^^^^^^^^^^^^^
file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/image_crop-0.3.0/lib/src/crop.dart:164:11: Error: Method not found: 'ImageStreamListener'.
          ImageStreamListener(_updateImage, onError: widget.onImageError);
          ^^^^^^^^^^^^^^^^^^^
file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/image_crop-0.3.0/lib/src/crop.dart:164:11: Error: The method 'ImageStreamListener' isn't defined for the class 'CropState'.
 - 'CropState' is from 'package:image_crop/image_crop.dart' ('file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/image_crop-0.3.0/lib/image_crop.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
          ImageStreamListener(_updateImage, onError: widget.onImageError);
          ^^^^^^^^^^^^^^^^^^^
file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/photo_view-0.4.2/lib/photo_view.dart:369:9: Error: Method not found: 'ImageStreamListener'.
        ImageStreamListener((ImageInfo info, bool synchronousCall) {
        ^^^^^^^^^^^^^^^^^^^
file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/photo_view-0.4.2/lib/photo_view.dart:369:9: Error: The method 'ImageStreamListener' isn't defined for the class '_PhotoViewState'.
 - '_PhotoViewState' is from 'package:photo_view/photo_view.dart' ('file:///Users/psh/.pub-cache/hosted/pub.flutter-io.cn/photo_view-0.4.2/lib/photo_view.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
        ImageStreamListener((ImageInfo info, bool synchronousCall) {
        ^^^^^^^^^^^^^^^^^^^
Compiler failed on /Users/psh/Desktop/todo-list-app-master/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by asjqkkkk** [comment]
@onlineDu 看一下你的flutter版本吧。不出意外是版本的问题，可以看一看readme最后面，有解决方案

**Comment by onlineDu** [comment]
flutter版本问题，机器Flutter (Channel dev, v1.6.0）需要修改引用API，已解决，感谢

**Comment by asjqkkkk** [comment]
@onlineDu 好的，已解决的issue别忘了关闭哦😄
