### ISSUE TITLE
合作交流

### ISSUE THREAD

**Issue by KelvinQQ** [asjqkkkk/flutter-todos#11]
你好，是否有商务合作的意向？有意向联系微信：history_zq

**Comment by asjqkkkk** [comment]
> 你好，是否有商务合作的意向？有意向联系微信：history_zq

谢谢😄，但是最近比较忙。😅

**Comment by KelvinQQ** [comment]
> > 你好，是否有商务合作的意向？有意向联系微信：history_zq
> 
> 谢谢😄，但是最近比较忙。😅

不会占用你很多时间，可以加个微信聊一下具体细节。即使达不成也没关系，就当交个朋友。哈哈~
