### ISSUE TITLE
垃圾回收时是否会有循环引用问题？

### ISSUE THREAD

**Issue by windows7lake** [asjqkkkk/flutter-todos#13]
Logic中持有model的引用，而model中也持有对logic的引用，在垃圾回收时，不会出现死锁而导致对象永远都无法释放吗？

**Comment by asjqkkkk** [comment]
这个不用担心，循环引用导致的问题只在很老的虚拟机上才会发生。并且我做了内存监控

这是在打开“任务详情”页面前的内存占用
![image](https://user-images.githubusercontent.com/30992818/69627297-53274a00-1085-11ea-9390-43b167fd9178.png)

然后是连续“打开->退出”很多次“任务详情”页面后的内存占用
![image](https://user-images.githubusercontent.com/30992818/69627415-8073f800-1085-11ea-8906-af72865ec3d5.png)

的确model和logic是相互引用的，并且logic在model中创建。但是logic中除了model不存储任何数据。而只要view被dispose了，那么model与logic自然就被抛弃了

good question！
后面会深入了解一下！
