### ISSUE TITLE
写篇博客介绍下flutter的编码心得啊

### ISSUE THREAD

**Issue by saviourdog** [asjqkkkk/flutter-todos#2]
写篇博客介绍下flutter的编码心得啊

**Comment by asjqkkkk** [comment]
这个..编码心得太抽象了,我也无从下手。
如果你没有看过我的博客的话可以去看一下：
[掘金博客](https://juejin.im/user/5badbff26fb9a05cef173bf0)
[简书博客](https://www.jianshu.com/u/26d861591896)
说不定会有帮助
