### ISSUE TITLE
flutter_svg >=0.13.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving faile

### ISSUE THREAD

**Issue by xudailong** [asjqkkkk/flutter-todos#3]
flutter_svg >=0.13.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving faile

 the package don't support this project

**Comment by asjqkkkk** [comment]
#1 问题与这个issue应该是一致的，解决方法请仔细阅读Readme的最后部分哦
