### ISSUE TITLE
想请教下，设计图是用什么画的呢

### ISSUE THREAD

**Issue by Jsharkc** [asjqkkkk/flutter-todos#4]
![image](https://user-images.githubusercontent.com/17465198/62532778-c6f3db80-b877-11e9-970a-0b53801078e2.png)
是直接在「蓝湖」上画的吗，还是 PS 呢

**Comment by asjqkkkk** [comment]
不是，是用的sketch，然后上传到蓝湖上

**Comment by Jsharkc** [comment]
哦哦哦，好的，感谢
