### ISSUE TITLE
debug模式下 右上角的debug标签无法去除

### ISSUE THREAD

**Issue by hanmeng1989** [asjqkkkk/flutter-todos#5]
看到你代码中写了debugShowCheckedModeBanner: false,这句代码，但是不起作用，依然会有debug标签，请问如何才能去除？

**Comment by asjqkkkk** [comment]
我并没有去掉debug标签啊😂
如果你想去掉的话在main.dart中的MaterialApp中加上debugShowCheckedModeBanner: false就好了

**Comment by hanmeng1989** [comment]
> 我并没有去掉debug标签啊😂
> 如果你想去掉的话在main.dart中的MaterialApp中加上debugShowCheckedModeBanner: false就好了

sorry,看错文件了，晕死~😂
