### ISSUE TITLE
项目很不错，希望能出一套这个项目的教程博客

### ISSUE THREAD

**Issue by lfcleo** [asjqkkkk/flutter-todos#6]

**Comment by asjqkkkk** [comment]
😂设计内容太多了，没有时间去写一套完整的内容。可以去看看我的掘金博客哦

**Comment by lfcleo** [comment]
没有找到关于掘金博客的信息😂

**Comment by asjqkkkk** [comment]
> 没有找到关于掘金博客的信息😂

可以看看第一个issue

**Comment by asjqkkkk** [comment]
> 没有找到关于掘金博客的信息😂

不对，是第二个😂

**Comment by luchengmei** [comment]
哇哦 请问有相应的教程吗

**Comment by asjqkkkk** [comment]
> 哇哦 请问有相应的教程吗

没有哦，可以去看看我的掘金博客

**Comment by luchengmei** [comment]
你掘金博客地址是啥

**Comment by asjqkkkk** [comment]
> 你掘金博客地址是啥

https://juejin.im/user/5badbff26fb9a05cef173bf0
