### ISSUE TITLE
完成后无法返回

### ISSUE THREAD

**Issue by cssword** [asjqkkkk/flutter-todos#7]
报个Bug啊，操作流程：

任务列表页面点击check完成任务，再点击左上角返回按钮，未能成功返回，页面就卡在这里了。
只能删除任务才能返回主页 :)

**Comment by asjqkkkk** [comment]
😂感谢反馈

不过从描述来看我也不好排查出bug的原因，不知道是否方便录制屏幕复现一下bug。
初步判断，应该是哪里报错了

**Comment by asjqkkkk** [comment]
bug原因我已经找到啦，等我修复！😄

**Comment by asjqkkkk** [comment]
bug已经修复，可以拉取master的最新分支解决问题。

或者等我发布下个app版本😂

感谢反馈！！！
