### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by wenboLee** [asjqkkkk/flutter-todos#8]
### 命名规范
1. pages文件夹内容太乱了，应该按照账号、todo、settings等来区分，放到子文件夹里面
2. 命名也是，思路不清晰，过几个月可能作者都忘了~

### dio
建议参考一篇文章做封装，链接：https://juejin.im/post/5c161e24e51d4546f83c8ae8

### 资源CDN
图片等资源，要做个CDN加速

**Comment by asjqkkkk** [comment]
#  1. 命名规范：
pages文件夹存放了所有的页面文件，随着项目的扩大，这里面的文件数量也在增多，没有去做一个分类，确实会影响阅读。

但是到底是根据功能来分类还是根据页面出入顺序来分类呢。我考虑了一下，选择了后者，因为这样更加直观，不需要太多思考。分类后效果如下
![image](https://user-images.githubusercontent.com/30992818/65022856-4b9c4400-d964-11e9-8358-15decfd59dc7.png)

# 2.命名思路不清晰：

这个问题我觉得见仁见智吧，在**readme**中我已经大致说明了项目的结构目录，命名方面我觉得是可以“顾名思义”的，至于思路嘛，我也不太清楚具体是指什么命名思路😂

# 3.dio ：

Dio的封装是沿用的我很久之前的封装了，属于“祖传代码”，也许后面会进一步优化一下，让可读性可和可扩展性更好。

# 4.图片资源CDN：

图片资源接口我是用的 **unsplash** 提供的api接口，因为是国外的网站，所以接口访问速度可能会偏慢，就像在github上面clone项目一样。至于使用CDN为api接口加速嘛...It's too expensive to do that



# 5.最后

非常感谢你的建议😊

也欢迎其他各位使用者提issue。

有求必应，有问必答！

**Comment by wenboLee** [comment]
👍👍
