### ISSUE TITLE
lib/logic/feedback_page_logic.dart:91:33: Error: Method not found: 'UploadFileInfo'.                   "avatar": new UploadFileInfo(new File(avatarPath), transFormName),                                 ^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by Juneor** [asjqkkkk/flutter-todos#9]
lib/logic/feedback_page_logic.dart:91:33: Error: Method not found: 'UploadFileInfo'.
                  "avatar": new UploadFileInfo(new File(avatarPath), transFormName),
                                ^^^^^^^^^^^^^^

**Comment by asjqkkkk** [comment]
能更加详细一些吗😂

**Comment by Juneor** [comment]
找不到UploadFileInfo 这个类呀

**Comment by Juneor** [comment]
估计漏提交了吧

**Comment by Juneor** [comment]
问题解决了，多谢，  可以加微信么？ 可以一块搞flutter

**Comment by asjqkkkk** [comment]
> 问题解决了，多谢， 可以加微信么？ 可以一块搞flutter

我最近应该会比较忙，可能没有时间去做这些😂
